steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    echo "Uploading updated files to Cloud Storage without deleting existing files..."
    gsutil -m rsync -r . gs://aiman-devops.site
    echo "Invalidating Cloud CDN cache..."
    gcloud compute url-maps invalidate-cdn-cache lb-crc --path "/*"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '900s'